### PR TITLE
Travis tests run integration

### PR DESCRIPTION
**Pull request by gabriellupu**
Add jasmine runner for phantomjs in order to be able to run the tests on the CI machine.

### CODE REVIEW

**Comment by gabriellupu** [comment]
The build is failing because 2 tests are failing (they are also failing when running locally):
https://travis-ci.org/Mangopay/cardregistration-js-kit/builds/199267446

```
2 test(s) FAILED:
Kit should return error from Payline if preregistrationData are incorrect.
Expected false to be truthy.
Kit should return error from leetchi script if registrationData are incorrect.
Expected false to be truthy.
```

How should we proceed @hobailey ? Do you want me to further investigate the failures?

**Comment by hobailey** [comment]
OK, thanks very much @gabriellupu. I think it's best that @andrzej-rojek takes a look please, as it was him who originally wrote the tests/kit.

**Comment by hobailey** [comment]
@gabriellupu tests are passing fine now - are you happy for us to merge in your changes?

**Comment by gabriellupu** [comment]
done! thanks!

**Pull request merged**
